// Generated by CoffeeScript 1.6.1

$(function() {
  $(document).on('click', '.popcorn-container a', function(e) {
    return e.preventDefault();
  });
  return $.contextMenu({
    selector: '.with-context-menu',
    callback: function(key) {
      return $(this).trigger(key);
    },
    items: {
      'setChapter': {
        name: "<span class='typcn typcn-edit'></span> Add/Edit chapter"
      },
      'deleteTimestamp': {
        'name': "<span class='typcn typcn-delete'></span> Delete timestamp"
      },
      'highlightTimestamp': {
        'name': "<span class='typcn typcn-zoom'></span> Highlight timestamp"
      }
    }
  });
});
