// Generated by CoffeeScript 1.6.1

$(function() {
  var $chapter;
  $chapter = $('.chapter');
  /*
         handle click chapter
  */

  $chapter.click(function(event) {
    var time;
    event.preventDefault();
    time = $(this).data('start');
    return root.pop.jumpTo(time);
  });
  /*
         set active chapter link if it's in correct chapter time
  */

  return $chapter.on('timeupdate', function(event, time) {
    var end, start;
    start = $(this).data('start');
    end = $(this).data('end');
    time = Math.floor(time);
    if (time >= start && time < end) {
      if (!$(this).hasClass('active')) {
        return $(this).addClass('active');
      }
    } else {
      return $(this).removeClass('active');
    }
  });
});
