// Generated by CoffeeScript 1.6.1

$(function() {
  var adjustBlocksContainerHeight;
  $('.block').resizable({
    stop: function(event, ui) {
      return $(this).trigger('resize');
    }
  }).draggable({
    handle: '.move',
    stop: function(event, ui) {
      return $(this).trigger('resize');
    }
  });
  $('.blocks').on('adjustBlocksContainerHeight', function() {
    return adjustBlocksContainerHeight();
  });
  return adjustBlocksContainerHeight = function() {
    var blocksContainerHeight, divBlocks, maxYposition;
    console.log('adjusting');
    divBlocks = $('.blocks');
    maxYposition = 0;
    $('.block').each(function() {
      var height, offsetTop, positionY;
      offsetTop = $(this).offset().top;
      height = $(this).height();
      positionY = offsetTop + height;
      if (positionY > maxYposition) {
        return maxYposition = positionY;
      }
    });
    blocksContainerHeight = maxYposition - divBlocks.offset().top;
    return divBlocks.height(blocksContainerHeight);
  };
});
