// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Bachelor.Models.Attachment = (function(_super) {

  __extends(Attachment, _super);

  function Attachment() {
    return Attachment.__super__.constructor.apply(this, arguments);
  }

  Attachment.prototype.defaults = {
    status: true,
    user_id: app.authUser.id
  };

  return Attachment;

})(Backbone.Model);

Bachelor.Collections.Attachments = (function(_super) {

  __extends(Attachments, _super);

  function Attachments() {
    return Attachments.__super__.constructor.apply(this, arguments);
  }

  Attachments.prototype.model = Bachelor.Models.Attachment;

  Attachments.prototype.url = "" + app.url + "/admin/attachments";

  return Attachments;

})(Backbone.Collection);
