// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Bachelor.Models.Block = (function(_super) {

  __extends(Block, _super);

  function Block() {
    return Block.__super__.constructor.apply(this, arguments);
  }

  Block.prototype.defaults = {
    status: true,
    master: false,
    lesson_id: Bachelor.lessonId,
    color: '#000000'
  };

  Block.prototype.initialize = function() {
    return this.set('color', getRandomColor());
  };

  Block.prototype.isMasterVideo = function() {
    return this.get('master');
  };

  Block.prototype["delete"] = function() {
    this.set('status', false);
    this.view.remove();
    this.rowView.remove();
    return Backbone.Events.trigger('setTimestampFalse', this.cid);
  };

  return Block;

})(Backbone.Model);

Bachelor.Collections.Blocks = (function(_super) {

  __extends(Blocks, _super);

  function Blocks() {
    return Blocks.__super__.constructor.apply(this, arguments);
  }

  Blocks.prototype.model = Bachelor.Models.Block;

  Blocks.prototype.url = "" + app.url + "/admin/blocks";

  return Blocks;

})(Backbone.Collection);
