// Generated by CoffeeScript 1.6.1
var _this = this,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Bachelor.Models.Lesson = (function(_super) {

  __extends(Lesson, _super);

  function Lesson() {
    var _this = this;
    this.getRelatedData = function(model, field) {
      return Lesson.prototype.getRelatedData.apply(_this, arguments);
    };
    return Lesson.__super__.constructor.apply(this, arguments);
  }

  Lesson.prototype.urlRoot = "" + app.url + "/admin/lessons";

  Lesson.prototype.defaults = {
    status: true
  };

  Lesson.prototype.initialize = function() {
    var _this = this;
    return this.fetch({
      success: function() {
        _this.setNewAttributes();
        return _this.lessonInfo = new Bachelor.Views.LessonView({
          model: _this
        });
      }
    });
  };

  Lesson.prototype.setNewAttributes = function() {
    var newAttributed;
    newAttributed = this.get('data').Lesson;
    return _.extend(this.attributes, newAttributed);
  };

  Lesson.prototype.getRelatedData = function(model, field) {
    return this.get('data')[model][field];
  };

  return Lesson;

})(Backbone.Model);
