// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Bachelor.Models.Timestamp = (function(_super) {

  __extends(Timestamp, _super);

  function Timestamp() {
    return Timestamp.__super__.constructor.apply(this, arguments);
  }

  Timestamp.prototype.defaults = {
    status: true,
    start: 0,
    end: 0
  };

  return Timestamp;

})(Backbone.Model);

Bachelor.Collections.Timestamps = (function(_super) {

  __extends(Timestamps, _super);

  function Timestamps() {
    return Timestamps.__super__.constructor.apply(this, arguments);
  }

  Timestamps.prototype.model = Bachelor.Models.Timestamp;

  Timestamps.prototype.url = "" + app.url + "/admin/timestamps";

  Timestamps.prototype.comparator = function(timestamp) {
    return timestamp.get('start');
  };

  return Timestamps;

})(Backbone.Collection);
