// Generated by CoffeeScript 1.6.1
var Colors, adjustBlocksContainerHeight, ajaxPost, capitalizeFirst, debug, getRandomColor;

debug = function(what) {
  return console.log(what);
};

capitalizeFirst = function(string) {
  return string.charAt(0).toUpperCase() + string.slice(1);
};

adjustBlocksContainerHeight = function() {
  var blocksContainerHeight, divBlocks, maxYposition, reserve;
  divBlocks = $('.blocks');
  maxYposition = 0;
  reserve = 50;
  $('.block').each(function() {
    var height, offsetTop, positionY;
    offsetTop = $(this).offset().top;
    height = $(this).height();
    positionY = offsetTop + height;
    if (positionY > maxYposition) {
      return maxYposition = positionY;
    }
  });
  blocksContainerHeight = maxYposition - divBlocks.offset().top;
  return divBlocks.height(blocksContainerHeight + reserve);
};

ajaxPost = function(url, data, onSuccess, onError) {
  return $.ajax({
    type: "POST",
    url: url,
    contentType: 'application/json',
    data: data,
    dataType: "json",
    success: onSuccess,
    error: onError
  });
};

getRandomColor = function() {
  if (Colors.current === Colors.names.length) {
    Colors.current = 0;
  }
  return Colors.names[Colors.current++];
};

Colors = {};

Colors.current = 0;

Colors.names = ["#a52a2a", "#0000ff", "#008000", "#ff0000", "#ff00ff", "#ffa500", "#800080", "#ffc0cb", "#00ff00", "#ffff00"];
