// Generated by CoffeeScript 1.6.1
var Colors, capitalizeFirst, debug, getRandomColor;

debug = function(what) {
  return console.log(what);
};

capitalizeFirst = function(string) {
  return string.charAt(0).toUpperCase() + string.slice(1);
};

getRandomColor = function() {
  if (Colors.current === Colors.names.length) {
    Colors.current = 0;
  }
  return Colors.names[Colors.current++];
};

Colors = {};

Colors.current = 0;

Colors.names = ["#a52a2a", "#0000ff", "#008000", "#00ff00", "#ff00ff", "#ffa500", "#ffc0cb", "#800080", "#800080", "#ff0000", "#ffff00"];
