// Generated by CoffeeScript 1.6.1
var root;

root = typeof exports !== "undefined" && exports !== null ? exports : this;

root.Bachelor = {
  Models: {},
  Collections: {},
  Routers: {},
  Views: {},
  lessonId: app.request.params.pass[0]
};
