// Generated by CoffeeScript 1.6.1
var _this = this,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Bachelor.Views.AddButtonsView = (function(_super) {

  __extends(AddButtonsView, _super);

  function AddButtonsView() {
    var _this = this;
    this.addAttachment = function(e) {
      return AddButtonsView.prototype.addAttachment.apply(_this, arguments);
    };
    this.addBlock = function(e) {
      return AddButtonsView.prototype.addBlock.apply(_this, arguments);
    };
    return AddButtonsView.__super__.constructor.apply(this, arguments);
  }

  AddButtonsView.prototype.el = $('.add-buttons');

  AddButtonsView.prototype.events = {
    'click .add-block': 'addBlock',
    'click .add-attachment': 'addAttachment'
  };

  AddButtonsView.prototype.addBlock = function(e) {
    var newBlock;
    e.preventDefault();
    newBlock = new Bachelor.Models.Block();
    return Bachelor.App.Collections.blocks.add(newBlock);
  };

  AddButtonsView.prototype.addAttachment = function(e) {
    return e.preventDefault();
  };

  return AddButtonsView;

})(Backbone.View);
