// Generated by CoffeeScript 1.6.1
var _this = this,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Bachelor.Views.BlocksRowsView = (function(_super) {

  __extends(BlocksRowsView, _super);

  function BlocksRowsView() {
    var _this = this;
    this.renderAllTimestamps = function() {
      return BlocksRowsView.prototype.renderAllTimestamps.apply(_this, arguments);
    };
    this.addTimestampView = function(timestamp) {
      return BlocksRowsView.prototype.addTimestampView.apply(_this, arguments);
    };
    this.addBlockRowView = function(block) {
      return BlocksRowsView.prototype.addBlockRowView.apply(_this, arguments);
    };
    return BlocksRowsView.__super__.constructor.apply(this, arguments);
  }

  BlocksRowsView.prototype.el = $('.blocks-rows');

  BlocksRowsView.prototype.initialize = function() {
    Bachelor.App.Collections.blocks.on('add', this.addBlockRowView);
    Bachelor.App.Collections.timestamps.on('add', this.addTimestampView);
    return Backbone.Events.on('renderAllTimestamps', this.renderAllTimestamps);
  };

  BlocksRowsView.prototype.addBlockRowView = function(block) {
    var view;
    if (!block.isMasterVideo()) {
      view = new Bachelor.Views.BlockRowView({
        model: block
      });
      return this.$el.append(view.render().el);
    }
  };

  BlocksRowsView.prototype.addTimestampView = function(timestamp) {
    var view;
    view = new Bachelor.Views.TimestampView({
      model: timestamp
    });
    return this.appendTimestampViewToBlockRow(timestamp);
  };

  BlocksRowsView.prototype.appendTimestampViewToBlockRow = function(timestamp) {
    var $blockRow, blockId, view;
    view = timestamp.view;
    blockId = timestamp.get('block_id');
    $blockRow = this.$el.find(".block-row[data-block-id=" + blockId + "]");
    return $blockRow.append(view.render().el);
  };

  BlocksRowsView.prototype.renderAllTimestamps = function() {
    var _this = this;
    return _.each(Bachelor.App.Collections.timestamps.models, function(timestamp) {
      timestamp.view.remove();
      return _this.appendTimestampViewToBlockRow(timestamp);
    });
  };

  return BlocksRowsView;

})(Backbone.View);
