// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Bachelor.Views.LessonView = (function(_super) {

  __extends(LessonView, _super);

  function LessonView() {
    return LessonView.__super__.constructor.apply(this, arguments);
  }

  LessonView.prototype.el = $('.lesson-info');

  LessonView.prototype.initialize = function() {
    return this.render();
  };

  LessonView.prototype.render = function() {
    return this.setInfoContent();
  };

  LessonView.prototype.setInfoContent = function() {
    var courseName, lessonName;
    lessonName = this.model.get('name');
    courseName = this.model.getRelatedData('Course', 'name');
    this.$('.lesson-name').text(lessonName);
    return this.$('.course-name').text(courseName);
  };

  return LessonView;

})(Backbone.View);
