// Generated by CoffeeScript 1.6.1
var _this = this,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Bachelor.Views.PinView = (function(_super) {

  __extends(PinView, _super);

  function PinView() {
    var _this = this;
    this.render = function() {
      return PinView.prototype.render.apply(_this, arguments);
    };
    return PinView.__super__.constructor.apply(this, arguments);
  }

  PinView.prototype.tagName = 'span';

  PinView.prototype.className = 'timeline-pin typicn location';

  PinView.prototype.ratio = null;

  PinView.prototype.initialize = function() {
    this.model.pinView = this;
    Backbone.Events.on('durationchange', this.render);
    return this.setContent();
  };

  PinView.prototype.render = function() {
    this.setRatio();
    this.setPosition();
    return this;
  };

  PinView.prototype.setContent = function() {
    var block, blockCid, blockIndexOf, color, marginTop;
    blockCid = this.model.get('blockCid');
    block = Bachelor.App.Collections.blocks.get(blockCid);
    blockIndexOf = Bachelor.App.Collections.blocks.indexOf(block);
    marginTop = (blockIndexOf - 1) * -13;
    color = block.get('color');
    return this.$el.css({
      color: color,
      marginTop: marginTop
    });
  };

  PinView.prototype.setPosition = function() {
    var position, start;
    if (this.ratio) {
      start = this.model.get('start');
      position = start / this.ratio;
      return this.$el.css('left', "" + position + "%");
    }
  };

  PinView.prototype.setRatio = function() {
    var _ref;
    return (_ref = this.ratio) != null ? _ref : this.ratio = Bachelor.App.Views.timelineView.ratio;
  };

  return PinView;

})(Backbone.View);
