// Generated by CoffeeScript 1.6.1
var _this = this,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Bachelor.Views.SaveButtonView = (function(_super) {

  __extends(SaveButtonView, _super);

  function SaveButtonView() {
    var _this = this;
    this.refreshLesson = function(e) {
      return SaveButtonView.prototype.refreshLesson.apply(_this, arguments);
    };
    this.onError = function(returnedData) {
      return SaveButtonView.prototype.onError.apply(_this, arguments);
    };
    this.onSuccess = function(returnedData) {
      return SaveButtonView.prototype.onSuccess.apply(_this, arguments);
    };
    this.saveLesson = function(e) {
      return SaveButtonView.prototype.saveLesson.apply(_this, arguments);
    };
    return SaveButtonView.__super__.constructor.apply(this, arguments);
  }

  SaveButtonView.prototype.el = $('.save-lesson');

  SaveButtonView.prototype.events = {
    'click .save-button': 'saveLesson',
    'click .refresh-lesson': 'refreshLesson'
  };

  SaveButtonView.prototype.saveLesson = function(e) {
    var blocks, blocksAjaxUrl, blocksData, timestamps, timestampsAjaxUrl, timestampsData;
    e.preventDefault();
    blocksAjaxUrl = Bachelor.App.Collections.blocks.url + "/saveAll";
    blocks = Bachelor.App.Collections.blocks;
    blocksData = JSON.stringify(blocks);
    timestampsAjaxUrl = Bachelor.App.Collections.timestamps.url + "/saveAll";
    timestamps = Bachelor.App.Collections.timestamps;
    timestampsData = JSON.stringify(timestamps);
    this.ajaxSend(blocksAjaxUrl, blocksData);
    return this.ajaxSend(timestampsAjaxUrl, timestampsData);
  };

  SaveButtonView.prototype.ajaxSend = function(url, data) {
    return $.ajax({
      type: "POST",
      url: url,
      contentType: 'application/json',
      data: data,
      dataType: "json",
      success: this.onSuccess,
      error: this.onError
    });
  };

  SaveButtonView.prototype.onSuccess = function(returnedData) {
    return debug(returnedData);
  };

  SaveButtonView.prototype.onError = function(returnedData) {
    return debug(returnedData);
  };

  SaveButtonView.prototype.refreshLesson = function(e) {
    e.preventDefault();
    return window.location.href = app.request.here;
  };

  return SaveButtonView;

})(Backbone.View);
